name: Deploy Nuxt App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt app
        run: npm run generate

      - name: Upload files to Hostinger
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-app
          path: dist

      - name: Deploy to Hostinger
        runs-on: ubuntu-latest
        needs: [deploy]
        env:
          FTP_HOST: ${{ secrets.HOSTINGER_FTP_HOST }}
          FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}

        steps:
          - name: Download artifact
            uses: actions/download-artifact@v3
            with:
              name: nuxt-app
              path: .

          - name: Connect to FTP server
            run: |
              ftp -n $FTP_HOST
              user $FTP_USERNAME $FTP_PASSWORD
          - name: Upload files to public directory
            run: |
              mkdir public
              cd public
              for file in *; do
                put "$file"
              done
          - name: Disconnect from FTP server
            run: bye
